export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// AUTH ACTION TYPES
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';

// REGISTER ACTION TYPES
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_CLEAN_AFTER_REDIRECT = 'REGISTER_CLEAN_AFTER_REDIRECT';

// GET OWN PROFILE ACTION TYPES
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_LOADING_SUCCESS = 'PROFILE_LOADING_SUCCESS';
export const PROFILE_EMPTY = 'PROFILE_EMPTY';

// REMOVE OWN PROFILE
export const PROFILE_CLEAR = 'PROFILE_CLEAR'

// CREATE PROFILE
export const PROFILE_EDIT_START = 'PROFILE_EDIT_START';
export const PROFILE_EDIT_FAIL = 'PROFILE_EDIT_FAIL';

// ADD EDUCATION TO PROFILE
export const PROFILE_ADD_EDU_START = "PROFILE_ADD_EDU_START";
export const PROFILE_ADD_EDU_SUCCESS = "PROFILE_ADD_EDU_SUCCESS";
export const PROFILE_ADD_EDU_FAIL = "PROFILE_ADD_EDU_FAIL";

// DELETE EDUCATION FROM PROFILE
export const PROFILE_DELETE_EDU_START = "PROFILE_DELETE_EDU_START";
export const PROFILE_DELETE_EDU_SUCCESS = "PROFILE_DELETE_EDU_SUCCESS";
export const PROFILE_DELETE_EDU_FAIL = "PROFILE_DELETE_EDU_FAIL";

// DELETE EDUCATION ITEM
export const PROFILE_REMOVE_EDU = "PROFILE_REMOVE_EDU";

// ADD PROFILE PHOTO
export const PROFILE_ADD_PHOTO_START = "PROFILE_ADD_PHOTO_START";
export const PROFILE_ADD_PHOTO_SUCCESS = "PROFILE_ADD_PHOTO_SUCCESS";
export const PROFILE_ADD_PHOTO_FAIL = "PROFILE_ADD_PHOTO_FAIL";

// DELETE PROFILE PHOTO
export const PROFILE_DELETE_PHOTO_START = "PROFILE_DELETE_PHOTO_START";
export const PROFILE_DELETE_PHOTO_SUCCESS = "PROFILE_DELETE_PHOTO_SUCCESS";
export const PROFILE_DELETE_PHOTO_FAIL = "PROFILE_DELETE_PHOTO_FAIL";

// ADD EXPERIENCE TO PROFILE
export const PROFILE_ADD_EXP_START = "PROFILE_ADD_EXP_START";
export const PROFILE_ADD_EXP_SUCCESS = "PROFILE_ADD_EXP_SUCCESS";
export const PROFILE_ADD_EXP_FAIL = "PROFILE_ADD_EXP_FAIL";

// DELETE EXPERIENCE FROM PROFILE
export const PROFILE_DELETE_EXP_START = "PROFILE_DELETE_EXP_START";
export const PROFILE_DELETE_EXP_SUCCESS = "PROFILE_DELETE_EXP_SUCCESS";
export const PROFILE_DELETE_EXP_FAIL = "PROFILE_DELETE_EXP_FAIL";

// DELETE EXPERIENCE ITEM
export const PROFILE_REMOVE_EXP = "PROFILE_REMOVE_EXP";

// ADD CONTACTS TO PROFILE
export const PROFILE_ADD_CONTACTS_START = "PROFILE_ADD_CONTACTS_START";
export const PROFILE_ADD_CONTACTS_SUCCESS = "PROFILE_ADD_CONTACTS_SUCCESS";
export const PROFILE_ADD_CONTACTS_FAIL = "PROFILE_ADD_CONTACTS_FAIL";

// ADD SOCIAL LINKS TO PROFILE
export const PROFILE_ADD_SOCIAL_START = "PROFILE_ADD_SOCIAL_START";
export const PROFILE_ADD_SOCIAL_SUCCESS = "PROFILE_ADD_SOCIAL_SUCCESS";
export const PROFILE_ADD_SOCIAL_FAIL = "PROFILE_ADD_SOCIAL_FAIL";

// GET ALL DEVELOPERS
export const DEVELOPERS_LOADING = 'DEVELOPERS_LOADING';
export const DEVELOPERS_NOT_FOUND = 'DEVELOPERS_NOT_FOUND';
export const DEVELOPERS_LOADED_SUCCESS = 'DEVELOPERS_LOADED_SUCCESS';

// FILTER DEVELOPERS BY SEARCH
export const DEVELOPES_SEARCH = 'DEVELOPES_SEARCH';

// GET PROFILE BY HANDLE
export const HANDLE_LOADING_START = 'HANDLE_LOADING_START';
export const HANDLE_LOADING_FAILED = 'HANDLE_LOADING_FAILED';
export const HANDLE_LOADING_SUCCESS = 'HANDLE_LOADING_SUCCESS';

// ADD A POST
export const POST_ADD_START = "POST_ADD_START";
export const POST_ADD_SUCCESS = "POST_ADD_SUCCESS";
export const POST_ADD_FAIL = "POST_ADD_FAIL";

// DELETE A POST
export const POST_DELETE_START = "POST_DELETE_START";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAIL = "POST_DELETE_FAIL";

// GET ALL POSTS
export const POST_GET_ALL_START = "POST_GET_ALL_START";
export const POST_GET_ALL_SUCCESS = "POST_GET_ALL_SUCCESS";
export const POST_GET_ALL_FAIL = "POST_GET_ALL_FAIL";

// FILTER POSTS BY TAG
export const POST_GET_BY_TAG = "POST_GET_BY_TAG";
export const POST_CLEAR_TAG = "POST_CLEAR_TAG";

// GET A POST
export const POST_GET_START = "POST_GET_START";
export const POST_GET_SUCCESS = "POST_GET_SUCCESS";
export const POST_GET_FAIL = "POST_GET_FAIL";

// ADD/REMOVE POST TO FAVORITES
export const POST_ADD_FAVORITE = "POST_ADD_FAVORITE";
export const POST_ADD_FAVORITE_FAILED = "POST_ADD_FAVORITE_FAILED";
export const POST_REMOVE_FAVORITE = "POST_REMOVE_FAVORITE";
export const POST_REMOVE_FAVORITE_FAILED = "POST_REMOVE_FAVORITE_FAILED";

// ADD A COMMENT
export const COMMENT_ADD_START = "COMMENT_ADD_START";
export const COMMENT_ADD_SUCCESS = "COMMENT_ADD_SUCCESS";
export const COMMENT_ADD_FAIL = "COMMENT_ADD_FAIL";

// DELETE A COMMENT
export const COMMENT_DELETE_START = "COMMENT_DELETE_START";
export const COMMENT_DELETE_SUCCESS = "COMMENT_DELETE_SUCCESS";
export const COMMENT_DELETE_FAIL = "COMMENT_DELETE_FAIL";

// ADD VACANCY
export const VACANCY_ADD_START = "VACANCY_ADD_START";
export const VACANCY_ADD_SUCCESS = "VACANCY_ADD_SUCCESS";
export const VACANCY_ADD_FAIL = "VACANCY_ADD_FAIL";
export const VACANCY_CLEAR_V_ID = "VACANCY_CLEAR_V_ID";

// LOAD ALL VACANCIES
export const VACANCY_LOAD_ALL_START = "VACANCY_LOAD_ALL_START";
export const VACANCY_LOAD_ALL_SUCCESS = "VACANCY_LOAD_ALL_SUCCESS";
export const VACANCY_LOAD_ALL_FAIL = "VACANCY_LOAD_ALL_FAIL";

// LOAD USERS VACANCIES
export const VACANCY_LOAD_MY_START = "VACANCY_LOAD_MY_START";
export const VACANCY_LOAD_MY_SUCCESS = "VACANCY_LOAD_MY_SUCCESS";
export const VACANCY_LOAD_MY_FAIL = "VACANCY_LOAD_MY_FAIL";

// LOAD VACANCY BY ID
export const VACANCY_LOAD_START = "VACANCY_LOAD_START";
export const VACANCY_LOAD_SUCCESS = "VACANCY_LOAD_SUCCESS";
export const VACANCY_LOAD_FAIL = "VACANCY_LOAD_FAIL";

// DELETE VACANCY BY ID
export const VACANCY_DELETE_START = "VACANCY_DELETE_START";
export const VACANCY_DELETE_SUCCESS = "VACANCY_DELETE_SUCCESS";
export const VACANCY_DELETE_FAIL = "VACANCY_DELETE_FAIL";

// CLEAR VACANCY IN REDUX STORE WHEN LEAVING PAGE
export const VACANCY_CLEAR_STORE = "VACANCY_CLEAR_STORE";

// LOAD USER RESPONSES
export const RESPONSE_SEND_START = "RESPONSE_SEND_START";
export const RESPONSE_SEND_SUCCESS = "RESPONSE_SEND_SUCCESS";
export const RESPONSE_SEND_FAIL = "RESPONSE_SEND_FAIL";

// SEARCH VACANCIES
export const VACANCIES_SEARCH = "VACANCIES_SEARCH";
